name: seldonite_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - newspaper3k
  - boto3
  - pyspark
  - selenium
  - spacy
  - gensim
  - google-api-python-client
  - conda-build
  - conda-pack
  - pandas
  - keras
  - pip
  - pip:
    - -e .
    - warcio
    - analytics-zoo

# tests
  - pytest>=6.2.3
