name: pyspark_conda_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - newspaper3k>=0.2.8
  - boto3>=1.18.62
  - pyspark>=3.1.2
  - selenium>=3.141.0
  - spacy>=3.1.3
  - gensim>=4.1.2
  - google-api-python-client>=2.28.0
  - conda-build
  - conda-pack
  - pip
  - pip:
    - .
    - warcio

# tests
  - pytest>=6.2.3
