name: seldonite
channels:
  - conda-forge
  - huggingface
  - pytorch
dependencies:
  - python=3.7
  - conda-build
  - conda-pack==0.3.1
  - newspaper3k
  - boto3
  - pyspark==3.1.2
  - selenium
  - spacy
  - nltk
  - networkx
  - transformers
  - pytorch==1.9.0
  - lemminflect>=0.2.1
  - gensim
  - google-api-python-client
  - pandas==1.2.5
  - numpy==1.21.4
  - six==1.16.0
  - py4j==0.10.9
  - aioredis<2.0.0
  - pytest
  - pip
  - pip:
    - -e .
    - warcio==1.7.4
    - ray
    - pyzmq
    - tensorflow>=2.1.0
    - bigdl-spark3
    - spark-nlp
