name: seldonite
channels:
  - conda-forge
dependencies:
  - python=3.7
  - conda-build
  - conda-pack
  - newspaper3k
  - boto3
  - pyspark>=3
  - selenium
  - spacy
  - gensim
  - google-api-python-client
  - pandas==1.0.3
  - keras
  - numpy==1.21.4
  - six==1.16.0
  - pytest
  - pip
  - pip:
    - -e .
    - warcio
